document.write("<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js' integrity='sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6' crossorigin='anonymous'></script>");
document.write("<script src='https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js'></script>");
document.write("<script src='https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js'></script>");
document.write("<script src='https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js'></script>");
document.write("<script src='https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js'></script>");
document.write("<script src='https://www.amcharts.com/lib/4/core.js'></script>");
document.write("<script src='https://www.amcharts.com/lib/4/charts.js'></script>");
document.write("<script src='https://www.amcharts.com/lib/4/themes/animated.js'></script>");
document.write("<script src='slick/slick.min.js'><\/script>");
document.write("<script src='js/charts.js'><\/script>");
document.write("<script src='js/assets.js'><\/script>");